[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

# String format for logging messages. If logger.datetimeFormat is also set,
# logger.messageFormat can contain the special string %(asctime)s that will be
# replaced with the date/time when each logging message is generated.
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"

[runner]
# Allows you to type a variable or string into the search bar to quickly filter options.
magicEnabled = true

# Run the Python Garbage Collector after each script execution. This can help to
# reduce memory usage in Streamlit apps, but could also cause app slowdowns.
postScriptGC = true

# Handle script rerun requests immediately, rather than waiting for script execution
# to reach a yield point. This makes Streamlit much more responsive to user
# interaction, but it can break apps that were written before this feature was
# introduced.
fastReruns = true

[server]
# List of folders that should not be watched for changes. This impacts both
# "Run on Save" and @st.cache.
# Relative paths will be taken as relative to the current working directory.
# Example: ['/home/user1/env', 'relative/path/to/folder']
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
# Allowed values: * "auto" : Streamlit will attempt to use the watchdog module, and
#                   falls back to polling if watchdog is not available.
#                 * "watchdog" : Force Streamlit to use the watchdog module.
#                 * "poll" : Force Streamlit to always use polling.
#                 * "none" : Streamlit will not watch files.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas,
# ensure that this is set to the same value across all replicas to ensure they all
# share the same secret.
# Default: randomly generated secret key.
# cookieSecret = "generated-secret-key"

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = true

# The address where the server will listen for client and browser connections.
# Use this if you want to bind the server to a specific address. If set, the
# server will only be accessible from this address, and not from any other
# address.
# Default: tries to use 'localhost', and if that fails, tries to use '0.0.0.0'.
# address =

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable from.
# Default: "/"
# baseUrlPath = ""

# Enables support for Cross-Origin Resource Sharing (CORS) for the given domains.
# Domain names should be separated by commas.
# Default: []
# enableCORS = false

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
maxMessageSize = 200

[browser]
# Whether to send usage statistics to Streamlit.
gatherUsageStats = true

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base = "light"

# Primary accent color for interactive elements.
# primaryColor = "#FF6B6B"

# Background color for the main content area.
# backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text.
# textColor = "#262730"